name: Move file to main folder

on:
  push:
    branches:
      - main

jobs:
  move-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository's code

      - name: Move file
        run: mv $GITHUB_WORKSPACE/test/file.txt $GITHUB_WORKSPACE/file.txt

      - name: Commit file changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add file.txt
          git commit -m "Move file to main folder" || echo "No changes to commit"
